[build]
  command = "npm run build"
  functions = "functions" # Netlity 서버리스 함수가 작성 된 디렉토리를 지정
  publish = "dist" # 프로젝트 빌드 결과의 디렉토리를 지정

[dev]
  framework = "#custom" # 감지할 프로젝트 유형을 지정합니다. 앱 서버 및 'targetPort' 옵션을 실행하는 명령어 옵션은..
  command = "npm run dev" #연결 할 프로젝트의 개발서버를 실행하는 명령어
  targetPort = 8080 # 연결 할 프로젝트 개발 서버 포트 지정
  port = 8888 ## 출력 할 Netlity 서버 포트를 지정
  publish = "dist" # 프로젝트의 정적 콘텐츠 디렉토리 지정
  autoLaunch = false # Netlity 서버가 준비되면 자동으로 브라우저를 오픈 할 것인지 결정